package com.ChatMe.Assignment.model;

import lombok.Data;
import lombok.Generated;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Data
@Document(collection = "users")
public class User {

    @Id
    @Generated // This annotation is used to indicate that the ID will be generated by the database
    private String uid;

    private String email;
    private String name;
    private String photoURL;
    private String provider;
}
